name: OnPoint
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3942652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5d8ea'
    - '#66b4cc'
    - '#ffffff'
    - '#1d3c55'
    - '#818f90'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
