layout_spectrum: 0.546595
typography_spectrum: 0.3942652
color:
  saturation: 0.07916479
  lightness: 0.2462652
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#010101'
    - '#303030'
    - '#767676'
    - '#C6C6C6'
  rhythmicContrast: 0.9920538
name: OnPoint
